# Test configuration: 1 human player + 4 OpenRouter AI players
# This uses OpenRouter's API to avoid Gemini rate limits

players:
  - name: Matt
    type: human
  
  - name: Alice
    type: agent
    llm_client: openrouter
  
  - name: Bob
    type: agent
    llm_client: openrouter
  
  - name: Charlie
    type: agent
    llm_client: openrouter
  
  - name: Diana
    type: agent
    llm_client: openrouter

# Optional roles (empty = use defaults: Merlin, Assassin, Servant x2, Minion)
optional_roles: []

# Enable detailed logging
enhanced_logging: true

# Random seed (optional - remove for random games)
# seed: 42
